{
 "title": "Hyperledger Fabric Common Dash Board",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "channel",
    "label": "channel",
    "query": {
     "query": "label_values(ledger_blockchain_height,channel)"
    }
   },
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(ledger_blockchain_height,job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Basic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Live Monitored Nodes",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "fabric_version" }
   ]
  },
  { "title": "Blocks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "ledger_blockchain_height_rate",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ledger_blockchain_height{channel=\"$channel\", job=~\"$job\"}[1m])"
    }
   ]
  },
  {
   "title": "Business transactions per channel, chaincode",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ledger_transaction_count{transaction_type=\"ENDORSER_TRANSACTION\",channel=\"$channel\"}"
    }
   ]
  },
  {
   "title": "ledger_blockchain_height",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ledger_blockchain_height{channel=\"$channel\", job=~\"$job\"}) by (job)",
     "legendFormat": "{{channel}} {{job}}"
    }
   ]
  },
  {
   "title": "Sum of business transactions per channel",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ledger_transaction_count{transaction_type=\"ENDORSER_TRANSACTION\",channel=\"$channel\", job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Block procesing time",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "ledger_block_processing_time_bucket",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "GRPC Connection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "grpc_server_stream_request_duration",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "grpc_server_stream_request_duration_bucket",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "grpc_server_unary_request_duration",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "expr": "grpc_server_unary_request_duration_bucket",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "GRPC Connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(grpc_comm_conn_closed{job=~\"$job\"}[5m])"
    },
    {
     "expr": "rate(grpc_comm_conn_opened{job=~\"$job\"}[5m])"
    },
    {
     "expr": "rate(grpc_server_stream_messages_received{job=~\"$job\"}[5m])"
    },
    {
     "expr": "rate(grpc_server_stream_messages_sent{job=~\"$job\"}[5m])"
    },
    {
     "expr": "rate(grpc_server_stream_requests_completed{job=~\"$job\"}[5m])"
    },
    {
     "expr": "rate(grpc_server_stream_requests_received{job=~\"$job\"}[5m])"
    },
    {
     "expr": "rate(grpc_server_unary_requests_completed{job=~\"$job\"}[5m])"
    },
    {
     "expr": "rate(grpc_server_unary_requests_received{job=~\"$job\"}[5m])"
    }
   ]
  },
  {
   "title": "GRPC Connections RealTime",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 44 },
   "targets": [
    { "expr": "grpc_comm_conn_closed" },
    { "expr": "grpc_comm_conn_opened" },
    {
     "expr": "grpc_server_stream_messages_received"
    },
    {
     "expr": "grpc_server_stream_messages_sent"
    },
    {
     "expr": "grpc_server_stream_requests_completed"
    },
    {
     "expr": "grpc_server_stream_requests_received"
    },
    {
     "expr": "grpc_server_unary_requests_completed"
    },
    {
     "expr": "grpc_server_unary_requests_received"
    }
   ]
  },
  { "title": "Logging", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "logging rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(logging_entries_checked{job=~\"$job\"}[5m])"
    },
    {
     "expr": "rate(logging_entries_written{job=~\"$job\"}[5m])"
    }
   ]
  }
 ]
}